git-unchange(1)

wipe out all uncommited changes to a file

## SYNOPSIS

git unchange <file>...

## DESCRIPTION

*git-unchange* wipes out all uncommitted changes to the given
files, whether they're currently staged for commit or not.

If given a directory, it will affect every file in that directory (recursively).

## BUGS

Report bugs to https://github.com/rwhogg/bobs-git-utils/issues

## SEE ALSO

git(1)
